project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Wenbin Hu"
  site-url: https://whu-hwb.github.io
  repo-url: https://github.com/whu-hwb/whu-hwb.github.io
  favicon: images/site-logo.png
  
  page-footer:
    left: |

    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "中文"
        href: Chinese.qmd

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细